project:
  type: website
  output-dir: docs   # GitHub Pages publicará desde /docs

website:
  title: "MetaCiencia"
  favicon: img/logo_MetaCiencia.png
  navbar:
    style: tab
    logo: img/logo_MetaCiencia.png
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Versión completa"
        href: presentacion_larga.html
      - text: "Versión resumida"
        href: presentacion_corta.html
        
format:
  html:
    theme: cosmo
    toc: false
    self-contained: false

lang: es